//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedTool {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resource {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resource() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeedTool.Resource", typeof(Resource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_folder {
			get {
				object obj = ResourceManager.GetObject("appbar.folder", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_folder_ellipsis {
			get {
				object obj = ResourceManager.GetObject("appbar.folder.ellipsis", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_folder_lock {
			get {
				object obj = ResourceManager.GetObject("appbar.folder.lock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_folder_open {
			get {
				object obj = ResourceManager.GetObject("appbar.folder.open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_folder_people {
			get {
				object obj = ResourceManager.GetObject("appbar.folder.people", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_folder_puzzle {
			get {
				object obj = ResourceManager.GetObject("appbar.folder.puzzle", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_folder_star {
			get {
				object obj = ResourceManager.GetObject("appbar.folder.star", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_heart {
			get {
				object obj = ResourceManager.GetObject("appbar.heart", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_heartbreak {
			get {
				object obj = ResourceManager.GetObject("appbar.heartbreak", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_home {
			get {
				object obj = ResourceManager.GetObject("appbar.home", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_ie {
			get {
				object obj = ResourceManager.GetObject("appbar.ie", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_movie_clapper {
			get {
				object obj = ResourceManager.GetObject("appbar.movie.clapper", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_movie_clapper_select {
			get {
				object obj = ResourceManager.GetObject("appbar.movie.clapper.select", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_movie_clapper_solid {
			get {
				object obj = ResourceManager.GetObject("appbar.movie.clapper.solid", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_movie_clapper_solid_select {
			get {
				object obj = ResourceManager.GetObject("appbar.movie.clapper.solid.select", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_music {
			get {
				object obj = ResourceManager.GetObject("appbar.music", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_music_live {
			get {
				object obj = ResourceManager.GetObject("appbar.music.live", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_music_select {
			get {
				object obj = ResourceManager.GetObject("appbar.music.select", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_navigate_next {
			get {
				object obj = ResourceManager.GetObject("appbar.navigate.next", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_navigate_previous {
			get {
				object obj = ResourceManager.GetObject("appbar.navigate.previous", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_new {
			get {
				object obj = ResourceManager.GetObject("appbar.new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_new_window {
			get {
				object obj = ResourceManager.GetObject("appbar.new.window", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_noentry {
			get {
				object obj = ResourceManager.GetObject("appbar.noentry", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_office_365 {
			get {
				object obj = ResourceManager.GetObject("appbar.office.365", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_os_ubuntu {
			get {
				object obj = ResourceManager.GetObject("appbar.os.ubuntu", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_os_windows {
			get {
				object obj = ResourceManager.GetObject("appbar.os.windows", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_os_windows_8 {
			get {
				object obj = ResourceManager.GetObject("appbar.os.windows.8", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_os_windowsphone {
			get {
				object obj = ResourceManager.GetObject("appbar.os.windowsphone", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_os_windowsphone_round {
			get {
				object obj = ResourceManager.GetObject("appbar.os.windowsphone.round", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_os_x64 {
			get {
				object obj = ResourceManager.GetObject("appbar.os.x64", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_os_x86 {
			get {
				object obj = ResourceManager.GetObject("appbar.os.x86", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_page_corner_cells {
			get {
				object obj = ResourceManager.GetObject("appbar.page.corner.cells", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_page_corner_folded {
			get {
				object obj = ResourceManager.GetObject("appbar.page.corner.folded", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_page_corner_folded_text {
			get {
				object obj = ResourceManager.GetObject("appbar.page.corner.folded.text", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_paper {
			get {
				object obj = ResourceManager.GetObject("appbar.paper", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_paperclip {
			get {
				object obj = ResourceManager.GetObject("appbar.paperclip", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_paperclip_rotated {
			get {
				object obj = ResourceManager.GetObject("appbar.paperclip.rotated", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_printer {
			get {
				object obj = ResourceManager.GetObject("appbar.printer", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_printer_blank {
			get {
				object obj = ResourceManager.GetObject("appbar.printer.blank", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_quote_left {
			get {
				object obj = ResourceManager.GetObject("appbar.quote.left", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_quote_right {
			get {
				object obj = ResourceManager.GetObject("appbar.quote.right", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_radar {
			get {
				object obj = ResourceManager.GetObject("appbar.radar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_redo {
			get {
				object obj = ResourceManager.GetObject("appbar.redo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_redo_curve {
			get {
				object obj = ResourceManager.GetObject("appbar.redo.curve", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_redo_point {
			get {
				object obj = ResourceManager.GetObject("appbar.redo.point", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_refresh {
			get {
				object obj = ResourceManager.GetObject("appbar.refresh", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_repeat {
			get {
				object obj = ResourceManager.GetObject("appbar.repeat", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_ribbon {
			get {
				object obj = ResourceManager.GetObject("appbar.ribbon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_ribbon_wave {
			get {
				object obj = ResourceManager.GetObject("appbar.ribbon.wave", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_rss {
			get {
				object obj = ResourceManager.GetObject("appbar.rss", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_scale {
			get {
				object obj = ResourceManager.GetObject("appbar.scale", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_scale_unbalanced {
			get {
				object obj = ResourceManager.GetObject("appbar.scale.unbalanced", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_settings {
			get {
				object obj = ResourceManager.GetObject("appbar.settings", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_share {
			get {
				object obj = ResourceManager.GetObject("appbar.share", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_share_open {
			get {
				object obj = ResourceManager.GetObject("appbar.share.open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_shield {
			get {
				object obj = ResourceManager.GetObject("appbar.shield", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_shield_alert {
			get {
				object obj = ResourceManager.GetObject("appbar.shield.alert", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_shuffle {
			get {
				object obj = ResourceManager.GetObject("appbar.shuffle", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sidebar_left_collapse {
			get {
				object obj = ResourceManager.GetObject("appbar.sidebar.left.collapse", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sidebar_left_expand {
			get {
				object obj = ResourceManager.GetObject("appbar.sidebar.left.expand", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sidebar_right_collapse {
			get {
				object obj = ResourceManager.GetObject("appbar.sidebar.right.collapse", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sidebar_right_expand {
			get {
				object obj = ResourceManager.GetObject("appbar.sidebar.right.expand", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sign_stop {
			get {
				object obj = ResourceManager.GetObject("appbar.sign.stop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sort {
			get {
				object obj = ResourceManager.GetObject("appbar.sort", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sort_alphabetical {
			get {
				object obj = ResourceManager.GetObject("appbar.sort.alphabetical", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sort_alphabetical_ascending {
			get {
				object obj = ResourceManager.GetObject("appbar.sort.alphabetical.ascending", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sort_alphabetical_descending {
			get {
				object obj = ResourceManager.GetObject("appbar.sort.alphabetical.descending", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sort_numeric {
			get {
				object obj = ResourceManager.GetObject("appbar.sort.numeric", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sort_numeric_ascending {
			get {
				object obj = ResourceManager.GetObject("appbar.sort.numeric.ascending", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sort_numeric_descending {
			get {
				object obj = ResourceManager.GetObject("appbar.sort.numeric.descending", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sound_0 {
			get {
				object obj = ResourceManager.GetObject("appbar.sound.0", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sound_1 {
			get {
				object obj = ResourceManager.GetObject("appbar.sound.1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sound_2 {
			get {
				object obj = ResourceManager.GetObject("appbar.sound.2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sound_3 {
			get {
				object obj = ResourceManager.GetObject("appbar.sound.3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sound_left_right {
			get {
				object obj = ResourceManager.GetObject("appbar.sound.left.right", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sound_mute {
			get {
				object obj = ResourceManager.GetObject("appbar.sound.mute", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sound_stereo {
			get {
				object obj = ResourceManager.GetObject("appbar.sound.stereo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_sound_stereo_stack {
			get {
				object obj = ResourceManager.GetObject("appbar.sound.stereo.stack", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_stairs_down {
			get {
				object obj = ResourceManager.GetObject("appbar.stairs.down", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_stairs_down_reflect_horizontal {
			get {
				object obj = ResourceManager.GetObject("appbar.stairs.down.reflect.horizontal", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_stairs_up {
			get {
				object obj = ResourceManager.GetObject("appbar.stairs.up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_stairs_up_reflect_horizontal {
			get {
				object obj = ResourceManager.GetObject("appbar.stairs.up.reflect.horizontal", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_star {
			get {
				object obj = ResourceManager.GetObject("appbar.star", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_star_add {
			get {
				object obj = ResourceManager.GetObject("appbar.star.add", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_star_delete {
			get {
				object obj = ResourceManager.GetObject("appbar.star.delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_star_invincible {
			get {
				object obj = ResourceManager.GetObject("appbar.star.invincible", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_star_minus {
			get {
				object obj = ResourceManager.GetObject("appbar.star.minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_stream {
			get {
				object obj = ResourceManager.GetObject("appbar.stream", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_text_sans {
			get {
				object obj = ResourceManager.GetObject("appbar.text.sans", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_text_script {
			get {
				object obj = ResourceManager.GetObject("appbar.text.script", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_text_serif {
			get {
				object obj = ResourceManager.GetObject("appbar.text.serif", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_text_size {
			get {
				object obj = ResourceManager.GetObject("appbar.text.size", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_thumb_up_add {
			get {
				object obj = ResourceManager.GetObject("appbar.thumb.up.add", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_thumb_up_delete {
			get {
				object obj = ResourceManager.GetObject("appbar.thumb.up.delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_thumb_up_minus {
			get {
				object obj = ResourceManager.GetObject("appbar.thumb.up.minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_thumbs_down {
			get {
				object obj = ResourceManager.GetObject("appbar.thumbs.down", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_thumbs_up {
			get {
				object obj = ResourceManager.GetObject("appbar.thumbs.up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tiles_nine {
			get {
				object obj = ResourceManager.GetObject("appbar.tiles.nine", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tiles_sixteen {
			get {
				object obj = ResourceManager.GetObject("appbar.tiles.sixteen", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tournament_bracket {
			get {
				object obj = ResourceManager.GetObject("appbar.tournament.bracket", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tournament_bracket_left {
			get {
				object obj = ResourceManager.GetObject("appbar.tournament.bracket.left", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tournament_bracket_right {
			get {
				object obj = ResourceManager.GetObject("appbar.tournament.bracket.right", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tournament_bracket_up {
			get {
				object obj = ResourceManager.GetObject("appbar.tournament.bracket.up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tower {
			get {
				object obj = ResourceManager.GetObject("appbar.tower", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_train {
			get {
				object obj = ResourceManager.GetObject("appbar.train", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_train_track {
			get {
				object obj = ResourceManager.GetObject("appbar.train.track", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_train_tunnel {
			get {
				object obj = ResourceManager.GetObject("appbar.train.tunnel", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_transit_hazard {
			get {
				object obj = ResourceManager.GetObject("appbar.transit.hazard", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tree {
			get {
				object obj = ResourceManager.GetObject("appbar.tree", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tree_leaf {
			get {
				object obj = ResourceManager.GetObject("appbar.tree.leaf", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tree_leaf_three {
			get {
				object obj = ResourceManager.GetObject("appbar.tree.leaf.three", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tree_pine {
			get {
				object obj = ResourceManager.GetObject("appbar.tree.pine", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_trophy {
			get {
				object obj = ResourceManager.GetObject("appbar.trophy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_truck {
			get {
				object obj = ResourceManager.GetObject("appbar.truck", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tux {
			get {
				object obj = ResourceManager.GetObject("appbar.tux", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tv {
			get {
				object obj = ResourceManager.GetObject("appbar.tv", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tv_news {
			get {
				object obj = ResourceManager.GetObject("appbar.tv.news", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tv_remote {
			get {
				object obj = ResourceManager.GetObject("appbar.tv.remote", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_tv_syfy {
			get {
				object obj = ResourceManager.GetObject("appbar.tv.syfy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_twitter_bird {
			get {
				object obj = ResourceManager.GetObject("appbar.twitter.bird", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_undo {
			get {
				object obj = ResourceManager.GetObject("appbar.undo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_undo_curve {
			get {
				object obj = ResourceManager.GetObject("appbar.undo.curve", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_undo_point {
			get {
				object obj = ResourceManager.GetObject("appbar.undo.point", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_upload {
			get {
				object obj = ResourceManager.GetObject("appbar.upload", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_user {
			get {
				object obj = ResourceManager.GetObject("appbar.user", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_user_add {
			get {
				object obj = ResourceManager.GetObject("appbar.user.add", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_user_delete {
			get {
				object obj = ResourceManager.GetObject("appbar.user.delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_user_minus {
			get {
				object obj = ResourceManager.GetObject("appbar.user.minus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_user_tie {
			get {
				object obj = ResourceManager.GetObject("appbar.user.tie", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_video_highdefinition {
			get {
				object obj = ResourceManager.GetObject("appbar.video.highdefinition", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_video_standarddefinition {
			get {
				object obj = ResourceManager.GetObject("appbar.video.standarddefinition", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_visualstudio {
			get {
				object obj = ResourceManager.GetObject("appbar.visualstudio", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_visualstudio_news {
			get {
				object obj = ResourceManager.GetObject("appbar.visualstudio.news", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_warning {
			get {
				object obj = ResourceManager.GetObject("appbar.warning", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_warning_circle {
			get {
				object obj = ResourceManager.GetObject("appbar.warning.circle", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_weather_chance {
			get {
				object obj = ResourceManager.GetObject("appbar.weather.chance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_weather_overcast {
			get {
				object obj = ResourceManager.GetObject("appbar.weather.overcast", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_weather_rain {
			get {
				object obj = ResourceManager.GetObject("appbar.weather.rain", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_weather_snow {
			get {
				object obj = ResourceManager.GetObject("appbar.weather.snow", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_weather_station {
			get {
				object obj = ResourceManager.GetObject("appbar.weather.station", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_weather_sun {
			get {
				object obj = ResourceManager.GetObject("appbar.weather.sun", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_weather_symbol {
			get {
				object obj = ResourceManager.GetObject("appbar.weather.symbol", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_weather_thunder {
			get {
				object obj = ResourceManager.GetObject("appbar.weather.thunder", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_youtube {
			get {
				object obj = ResourceManager.GetObject("appbar.youtube", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_youtube_play {
			get {
				object obj = ResourceManager.GetObject("appbar.youtube.play", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap appbar_zune {
			get {
				object obj = ResourceManager.GetObject("appbar.zune", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to id|/id
		///title|/title
		///link-type|/link[@rel=&apos;self&apos;]/@type
		///link-href|/link[@rel=&apos;self&apos;]/@href
		///link-alt-type|/link[@rel=&apos;alternate&apos;]/@type
		///link-alt-href|/link[@rel=&apos;alternate&apos;]/@href
		///author-name|/author/name
		///author-email|/author/email
		///author-uri|/author/uri
		///rights|/rights
		///icon|/icon
		///logo|/logo
		///subtitle|/subtitle
		///updated|/updated
		///entry-id|/id
		///entry-updated|/updated
		///entry-link-rel|/link/@rel
		///entry-link-type|/link/@type
		///entry-link-href|/link/@href
		///entry-title|/title
		///entry-subtitle|/subtitle
		///ent [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string Dic_AtomFeed {
			get {
				return ResourceManager.GetString("Dic AtomFeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to title|/title
		///pubDate|/pubDate
		///link|/link
		///enclosure|/enclosure/@url
		///enclosure-length|/enclosure/@length
		///enclosure-type|/enclosure/@type
		///content|/content:encoded
		///comments|/comments
		///creator|/creator
		///description|/description.
		/// </summary>
		internal static string Dic_RssFeed {
			get {
				return ResourceManager.GetString("Dic RssFeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to id|/xmlroot:id
		///title|/xmlroot:title
		///published|/xmlroot:published
		///updated|/xmlroot:updated
		///creator|/xmlroot:creator
		///content|/xmlroot:content
		///link|/xmlroot:link[@rel=&apos;self&apos;]/@href
		///enclosure|/xmlroot:enclosure/@url
		///img|/media:group/media:thumbnail[1]/@url.
		/// </summary>
		internal static string Dic_YtFeed {
			get {
				return ResourceManager.GetString("Dic YtFeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to     &lt;style&gt;
		///body,
		///p,
		///h2,
		///pre { font-family: &apos;Segoe UI&apos;; }
		///h2 {font-family: &apos;Segoe UI Light&apos;;}
		///body { background-color: white; }
		///    &lt;/style&gt;.
		/// </summary>
		internal static string html_css {
			get {
				return ResourceManager.GetString("html css", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;html lang=&quot;en-US&quot;&gt;
		///  &lt;head&gt;
		///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
		///    &lt;title&gt;@{title}&lt;/title&gt;@{style}
		///  &lt;/head&gt;
		///&lt;body&gt;@{content}&lt;/body&gt;
		///&lt;/html&gt;.
		/// </summary>
		internal static string Html_Master {
			get {
				return ResourceManager.GetString("Html Master", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 
		///&lt;!--&lt;img src=&apos;@{img}&apos; align=&quot;right&quot;&gt;--&gt;
		///&lt;h2&gt;&lt;span style=&quot;float:right; font-size: 10px;&quot;&gt;@{html-link}@{html-enclosure-break}@{html-enclosure}&lt;/span&gt;@{title}&lt;/h2&gt;
		///@{date}&lt;br/&gt;
		///&lt;!--&lt;tt&gt;&lt;/tt&gt;--&gt;
		///&lt;div&gt;@{description}&lt;/div&gt;
		///.
		/// </summary>
		internal static string Html_Rss_Template {
			get {
				return ResourceManager.GetString("Html Rss Template", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;html&gt;
		///&lt;title&gt;
		///@{title}
		///&lt;/title&gt;
		///&lt;style&gt;
		///body,
		///p,
		///h2,
		///pre { font-family: segoe ui; }
		///h2 {font-family: &apos;Segoe UI Light&apos;;}
		///body { background-color: white; }
		///&lt;/style&gt;
		///&lt;/head&gt;
		///&lt;body&gt;
		///&lt;img src=&apos;@{img}&apos; align=&quot;right&quot; width=&quot;240&quot;&gt;
		///&lt;h2&gt;@{title}&lt;/h2&gt;
		///&lt;tt&gt;@{links}&lt;/tt&gt;
		///@{date}&lt;br/&gt;
		///@{description}
		///&lt;hr /&gt;
		///&lt;iframe width=&quot;640&quot; height=&quot;360&quot; src=&quot;//www.youtube.com/embed/@{video-id}&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;
		///&lt;/body&gt;
		///&lt;/html&gt;.
		/// </summary>
		internal static string Html_Youtube_Old_Template {
			get {
				return ResourceManager.GetString("Html Youtube Old Template", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 
		///    &lt;img src=&apos;@{img}&apos; align=&quot;right&quot; width=&quot;240&quot;&gt;
		///    &lt;h2&gt;@{title}&lt;/h2&gt;
		///    &lt;tt&gt;@{links}&lt;/tt&gt;
		///    @{date}&lt;br/&gt;
		///    @{description}
		///    &lt;hr /&gt;
		///    &lt;h2&gt;IFrame-Embed&lt;/h2&gt;
		///    &lt;iframe src=&apos;http://www.youtube.com/embed/@{video-id}&apos;&gt;&lt;/iframe&gt;
		///    &lt;h2&gt;Object-Embed&lt;/h2&gt;
		///    &lt;object width=&quot;560&quot; height=&quot;315&quot;&gt;
		///      &lt;param name=&quot;movie&quot; value=&quot;http://www.youtube.com/v/@{video-id}?version=3&amp;amp;hl=en_US&amp;amp;rel=0&quot;&gt;&lt;/param&gt;
		///      &lt;param name=&quot;allowFullScreen&quot; value=&quot;true&quot;&gt;&lt;/param&gt;
		///      &lt;param name=&quot;allowscri [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string Html_YouTube_Template {
			get {
				return ResourceManager.GetString("Html YouTube Template", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to CREATE TABLE [feeds] (
		///	[id]		INTEGER PRIMARY KEY AUTOINCREMENT,
		///	[ddt]		DATETIME DEFAULT NULL,
		///	[udt]		DATETIME DEFAULT NULL,
		///	[title]		VARCHAR DEFAULT NULL,
		///	[alt]		VARCHAR DEFAULT NULL,
		///	[note]		VARCHAR DEFAULT NULL,
		///	[url]		VARCHAR DEFAULT NULL,
		///	[content]		VARCHAR DEFAULT NULL
		///);.
		/// </summary>
		internal static string Sqlite_Db_Create {
			get {
				return ResourceManager.GetString("Sqlite Db Create", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to feeds.sqlite.
		/// </summary>
		internal static string Sqlite_Db_Feeds {
			get {
				return ResourceManager.GetString("Sqlite Db Feeds", resourceCulture);
			}
		}
	}
}
