//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedTool {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resource {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resource() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeedTool.Resource", typeof(Resource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.FFFFF.
		/// </summary>
		internal static string DateFormatDownloader {
			get {
				return ResourceManager.GetString("DateFormatDownloader", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to id|/id
		///title|/title
		///link-type|/link[@rel=&apos;self&apos;]/@type
		///link-href|/link[@rel=&apos;self&apos;]/@href
		///link-alt-type|/link[@rel=&apos;alternate&apos;]/@type
		///link-alt-href|/link[@rel=&apos;alternate&apos;]/@href
		///author-name|/author/name
		///author-email|/author/email
		///author-uri|/author/uri
		///rights|/rights
		///icon|/icon
		///logo|/logo
		///subtitle|/subtitle
		///updated|/updated
		///entry-id|/id
		///entry-updated|/updated
		///entry-link-rel|/link/@rel
		///entry-link-type|/link/@type
		///entry-link-href|/link/@href
		///entry-title|/title
		///entry-subtitle|/subtitle
		///ent [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string Dic_AtomFeed {
			get {
				return ResourceManager.GetString("Dic AtomFeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to title|/title
		///pubDate|/pubDate
		///link|/link
		///enclosure|/enclosure/@url
		///enclosure-length|/enclosure/@length
		///enclosure-type|/enclosure/@type
		///content|/content:encoded
		///comments|/comments
		///creator|/creator
		///description|/description.
		/// </summary>
		internal static string Dic_RssFeed {
			get {
				return ResourceManager.GetString("Dic RssFeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to id|/xmlroot:id
		///title|/xmlroot:title
		///published|/xmlroot:published
		///updated|/xmlroot:updated
		///creator|/xmlroot:creator
		///content|/xmlroot:content
		///link|/xmlroot:link[@rel=&apos;self&apos;]/@href
		///enclosure|/xmlroot:enclosure/@url
		///img|/media:group/media:thumbnail[1]/@url.
		/// </summary>
		internal static string Dic_YtFeed {
			get {
				return ResourceManager.GetString("Dic YtFeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to     &lt;object&gt;
		///      &lt;param name=&quot;movie&quot; value=&quot;http://www.youtube.com/v/@{video-id}?version=3&amp;amp;hl=en_US&amp;amp;rel=0&quot;&gt;&lt;/param&gt;
		///      &lt;param name=&quot;allowFullScreen&quot; value=&quot;true&quot;&gt;&lt;/param&gt;
		///      &lt;param name=&quot;allowscriptaccess&quot; value=&quot;always&quot;&gt;&lt;/param&gt;
		///      &lt;embed src=&quot;http://www.youtube.com/v/@{video-id}?version=3&amp;amp;hl=en_US&amp;amp;rel=0&quot; type=&quot;application/x-shockwave-flash&quot; allowscriptaccess=&quot;always&quot; allowfullscreen=&quot;true&quot;&gt;&lt;/embed&gt;
		///    &lt;/object&gt;.
		/// </summary>
		internal static string Flash_Object {
			get {
				return ResourceManager.GetString("Flash Object", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to     &lt;object width=&quot;560&quot; height=&quot;315&quot;&gt;
		///      &lt;param name=&quot;movie&quot; value=&quot;http://www.youtube.com/v/@{video-id}?version=3&amp;amp;hl=en_US&amp;amp;rel=0&quot;&gt;&lt;/param&gt;
		///      &lt;param name=&quot;allowFullScreen&quot; value=&quot;true&quot;&gt;&lt;/param&gt;
		///      &lt;param name=&quot;allowscriptaccess&quot; value=&quot;always&quot;&gt;&lt;/param&gt;
		///      &lt;embed src=&quot;http://www.youtube.com/v/@{video-id}?version=3&amp;amp;hl=en_US&amp;amp;rel=0&quot; width=&quot;560&quot; height=&quot;315&quot; type=&quot;application/x-shockwave-flash&quot; allowscriptaccess=&quot;always&quot; allowfullscreen=&quot;true&quot;&gt;&lt;/embed&gt;
		///    &lt;/object&gt;.
		/// </summary>
		internal static string Flash_Object_560x315 {
			get {
				return ResourceManager.GetString("Flash Object 560x315", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to     &lt;object width=&quot;100%&quot; height=&quot;420&quot; id=&quot;movie&quot; class=&quot;mov420&quot;&gt;
		///      &lt;param name=&quot;movie&quot; value=&quot;http://www.youtube.com/v/@{video-id}?version=3&amp;amp;hl=en_US&amp;amp;rel=0&quot;&gt;&lt;/param&gt;
		///      &lt;param name=&quot;allowFullScreen&quot; value=&quot;true&quot;&gt;&lt;/param&gt;
		///      &lt;param name=&quot;allowscriptaccess&quot; value=&quot;always&quot;&gt;&lt;/param&gt;
		///      &lt;embed src=&quot;http://www.youtube.com/v/@{video-id}?version=3&amp;amp;hl=en_US&amp;amp;rel=0&quot; width=&quot;100%&quot; height=&quot;420&quot; type=&quot;application/x-shockwave-flash&quot; allowscriptaccess=&quot;always&quot; allowfullscreen=&quot;true&quot;&gt;&lt;/embed&gt; [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string Flash_Object_Old2 {
			get {
				return ResourceManager.GetString("Flash Object Old2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to     &lt;object width=&quot;100%&quot; height=&quot;420&quot; id=&quot;movie&quot; class=&quot;mov420&quot;&gt;
		///      &lt;param name=&quot;movie&quot; value=&quot;http://www.youtube.com/v/@{video-id}?version=3&amp;amp;hl=en_US&amp;amp;rel=0&quot;&gt;&lt;/param&gt;
		///      &lt;param name=&quot;allowFullScreen&quot; value=&quot;true&quot;&gt;&lt;/param&gt;
		///      &lt;param name=&quot;allowscriptaccess&quot; value=&quot;always&quot;&gt;&lt;/param&gt;
		///      &lt;embed src=&quot;http://www.youtube.com/v/@{video-id}?version=3&amp;amp;hl=en_US&amp;amp;rel=0&quot; width=&quot;100%&quot; height=&quot;420&quot; type=&quot;application/x-shockwave-flash&quot; allowscriptaccess=&quot;always&quot; allowfullscreen=&quot;true&quot;&gt;&lt;/embed&gt; [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string Flash_Object_WIDTHx420 {
			get {
				return ResourceManager.GetString("Flash Object WIDTHx420", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 
		///@import url(http://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic,700italic&amp;subset=latin-ext,cyrillic,latin,cyrillic-ext);
		///@import url(http://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic,700italic&amp;subset=latin-ext,cyrillic,latin,cyrillic-ext);
		///      body, p, h2, pre, pre &gt; code  { font-family: &apos;PT Serif&apos;, &apos;Segoe UI&apos;; }
		///      pre &gt; code  { font-size: 11pt; }
		///      h2 {font-family: &apos;PT Serif&apos;, &apos;Segoe UI Light&apos;;}
		///      body { background-color: white; }
		///      /**
		///       * rule [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string html_css {
			get {
				return ResourceManager.GetString("html css", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 
		///    &lt;script src=&quot;http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js&quot;&gt;&lt;/script&gt;
		///    &lt;script language=&apos;javascript&apos;&gt;
		///      $(document).ready(function(){
		///        $(&apos;li#cf1&apos;).click(function(){ changeStyle(&quot;format-code&quot;); });
		///        $(&apos;li#cf2&apos;).click(function(){ changeStyle(&quot;format-mode&quot;); });
		///        $(&apos;li#cf3&apos;).click(function(){ changeStyle(&quot;code-format&quot;); });
		///      });
		///      function changeStyle(nam) { $(&quot;section#content&quot;).removeAttr(&quot;class&quot;).attr(&quot;class&quot;,nam); }
		///    &lt;/script&gt;.
		/// </summary>
		internal static string Html_Javascript {
			get {
				return ResourceManager.GetString("Html Javascript", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;html lang=&quot;en-US&quot;&gt;
		///  &lt;head&gt;
		///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
		///    &lt;title&gt;@{title}&lt;/title&gt;
		///    &lt;style&gt;@{style}
		///    &lt;/style&gt;
		///    &lt;!----&gt;@{html-javascript}
		///  &lt;/head&gt;
		///  &lt;body&gt;@{content}
		///  &lt;/body&gt;
		///&lt;/html&gt;.
		/// </summary>
		internal static string Html_Master {
			get {
				return ResourceManager.GetString("Html Master", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 
		///&lt;!--&lt;img src=&apos;@{img}&apos; align=&quot;right&quot;&gt;--&gt;
		///&lt;h2&gt;&lt;span style=&quot;float:right; font-size: 10px;&quot;&gt;@{html-link}@{html-enclosure-break}@{html-enclosure}&lt;/span&gt;@{title}&lt;/h2&gt;
		///@{date}&lt;br/&gt;
		///&lt;!--&lt;tt&gt;&lt;/tt&gt;--&gt;
		///&lt;div&gt;@{description}&lt;/div&gt;
		///.
		/// </summary>
		internal static string Html_Rss_Template {
			get {
				return ResourceManager.GetString("Html Rss Template", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;html&gt;
		///&lt;title&gt;
		///@{title}
		///&lt;/title&gt;
		///&lt;style&gt;
		///body,p,h2,pre { font-family: segoe ui; }
		///h2 { font-family: &apos;Segoe UI Light&apos;; }
		///body { background-color: white; }
		///&lt;/style&gt;
		///&lt;/head&gt;
		///&lt;body&gt;
		///&lt;img src=&quot;@{img}&quot; align=&quot;right&quot; width=&quot;240&quot;&gt;
		///&lt;h2&gt;@{title}&lt;/h2&gt;
		///&lt;tt&gt;@{links}&lt;/tt&gt;
		///@{date}&lt;br/&gt;
		///@{description}
		///&lt;hr /&gt;
		///&lt;iframe width=&quot;640&quot; height=&quot;360&quot; src=&quot;//www.youtube.com/embed/@{video-id}&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;
		///&lt;/body&gt;
		///&lt;/html&gt;.
		/// </summary>
		internal static string Html_Youtube_Old_Template {
			get {
				return ResourceManager.GetString("Html Youtube Old Template", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 
		///    &lt;img src=&apos;@{img}&apos; align=&quot;right&quot; width=&quot;240&quot;&gt;
		///    &lt;h2&gt;@{title}&lt;/h2&gt;
		///    &lt;tt&gt;@{links}&lt;/tt&gt;
		///    @{date}&lt;br/&gt;
		///    &lt;ul class=&apos;ulmenu&apos;&gt;
		///       &lt;li id=&quot;cf1&quot;&gt;
		///       CODE
		///       &lt;/li&gt; &lt;li id=&quot;cf2&quot;&gt;
		///       PRE/WRAP
		///       &lt;/li&gt; &lt;li id=&quot;cf3&quot;&gt;
		///       Show Method #3
		///       &lt;/li&gt;
		///    &lt;/ul&gt;
		///    &lt;section id=&quot;content&quot; class=&quot;format-mode&quot;&gt;@{description}
		///    &lt;/section&gt;
		///    &lt;hr /&gt;@{flash-object}.
		/// </summary>
		internal static string Html_YouTube_Template {
			get {
				return ResourceManager.GetString("Html YouTube Template", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to CREATE TABLE [feeds] (
		///	[id]		INTEGER PRIMARY KEY AUTOINCREMENT,
		///	[ddt]		DATETIME DEFAULT NULL,
		///	[udt]		DATETIME DEFAULT NULL,
		///	[title]		VARCHAR DEFAULT NULL,
		///	[alt]		VARCHAR DEFAULT NULL,
		///	[note]		VARCHAR DEFAULT NULL,
		///	[url]		VARCHAR DEFAULT NULL,
		///	[content]		VARCHAR DEFAULT NULL
		///);.
		/// </summary>
		internal static string Sqlite_Db_Create {
			get {
				return ResourceManager.GetString("Sqlite Db Create", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to feeds.sqlite.
		/// </summary>
		internal static string Sqlite_Db_Feeds {
			get {
				return ResourceManager.GetString("Sqlite Db Feeds", resourceCulture);
			}
		}
	}
}
