using System;
using System.Data;
using System.Linq;

namespace FeedTool
{
	//
	// Generated by a tool : 02/08/2013 07:23.10 AM
	// (Generator tool)
	// and modified by hand of course.
	// ------------------------
	/// <summary>
	/// 
	/// </summary>
	public class FeedListItem
	{
		#region Queries
		/// <summary> not that we need it or anything </summary>
		internal const string Insert_Feeds = @"INSERT INTO [feeds] (
	[udt],
	[ddt],
	[title],
	[alt],
	[note],
	[url],
	[content])
VALUES(
	@udt,
	@ddt,
	@title,
	@alt,
	@note,
	@url,
	@content);";
		/// <summary> not that we need it or anything </summary>
		internal const string Update_Feeds = @"UPDATE [feeds] SET
		[udt] = @udt,
		[ddt] = @ddt,
		[title] = @title,
		[alt] = @alt,
		[note] = @note,
		[url] = @url,
		[content] = @content
WHERE [id] = @xid;";
		/// <summary> not that we need it or anything </summary>
		internal const string Select_Feeds = @"Select * From feeds;";
		#endregion
		#region Properties
		public int? id { get;set; }
		public DateTime? udt { get;set; }
		public DateTime? ddt { get;set; }
		public string title { get;set; }
		public string alt { get;set; }
		public string note { get;set; }
		public string url { get;set; }
		public string content { get;set; }
		#endregion
		#region Constructors

		public FeedListItem(DataRowView row)
		{
			if (row["id"]!=DBNull.Value) this.id = row["id"] as int?;
			if (row["udt"]!=DBNull.Value) this.udt = row["udt"] as DateTime?;
			if (row["ddt"]!=DBNull.Value) this.ddt = row["ddt"] as DateTime?;
			if (row["title"]!=DBNull.Value) this.title = row["title"] as string;
			if (row["alt"]!=DBNull.Value) this.alt = row["alt"] as string;
			if (row["note"]!=DBNull.Value) this.note = row["note"] as string;
			if (row["url"]!=DBNull.Value) this.url = row["url"] as string;
			if (row["content"]!=DBNull.Value) this.content = row["content"] as string;
		}

		public FeedListItem(){}
		/// <summary>
		/// Used for cloning operations.
		/// <para>Particularly for Insert/Update SQL Queries due to the readonly PRIMARY KEY value.</para>
		/// </summary>
		public FeedListItem(FeedListItem value)
		{
			this.id = value.id;
			this.udt = value.udt;
			this.ddt = value.ddt;
			this.title = value.title;
			this.alt = value.alt;
			this.note = value.note;
			this.url = value.url;
			this.content = value.content;
		}
		#region NONONO
		#if NONONO
		
		/// <summary>
		/// Used for cloning operations.
		/// <para>Particularly for Insert/Update SQL Queries due to the readonly PRIMARY KEY value.</para>
		/// </summary>
		public FeedListItem(FeedListItem value)
		{
			this.id = value.id;
			this.SetFields(value);
		}
		#endif
		#endregion
		#endregion
		#region Utils

		/// <summary>
		/// Used for cloning operations.
		/// <para>Particularly for Insert/Update SQL Queries due to the readonly PRIMARY KEY value.</para>
		/// </summary>
		public void SetFields(FeedListItem value)
		{
			this.udt = value.udt;
			this.ddt = value.ddt;
			this.title = value.title;
			this.alt = value.alt;
			this.note = value.note;
			this.url = value.url;
			this.content = value.content;
		}
		#region IF SQLITE
		#if SQLITE
		// TODO: add if (usePrimary) to the primary key
		// an insert statement would not use or contain
		// a primary key value (or would contain a null,
		// hence we provide the oppertunity to neglect
		// it here.
		public SQLiteCommand Parameterize(SQLiteCommand cmd, bool usePrimary)
		{
			if (usePrimary) cmd.Parameters.AddWithValue("@xid", this.id);
			cmd.Parameters.AddWithValue("@udt", this.udt);
			cmd.Parameters.AddWithValue("@ddt", this.ddt);
			cmd.Parameters.AddWithValue("@title", this.title);
			cmd.Parameters.AddWithValue("@alt", this.alt);
			cmd.Parameters.AddWithValue("@note", this.note);
			cmd.Parameters.AddWithValue("@url", this.url);
			cmd.Parameters.AddWithValue("@content", this.content);
			return cmd;
		}
		#endif
		#endregion
		#endregion
	}

}
