/* oio * 5/29/2014 * Time: 5:55 AM
*/
using System;
using System.Collections.Generic;
using System.Cor3.Data.Engine;
using System.Data;
using System.Data.SQLite;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
namespace crudbook
{
	// based on modern-ui CommandBase?
	
	// Generated by a tool : 05/29/2014 05:54:29.807 AM
	// ------------------------
	public partial class BookMine
	{
		public DataFileLoader Loader {
			get { return loader; }
			set { loader = value; }
		} DataFileLoader loader;
		
		
		
		static public implicit operator BookMine(DataRowView row) { return BookMine.FromRowView(row); }
		// a custom variable
		public string SQLiteDataPath
		{
			get;
			internal set;
		}
		static public string StringForBookMine(string input, BookMine m)
		{
			return input
				.Replace("{id}", string.Format("{0}",m.id))
				.Replace("{publishdate}", string.Format("{0}",m.publishdate))
				.Replace("{title}", string.Format("{0}",m.title))
				.Replace("{author}", string.Format("{0}",m.author))
				.Replace("{publisher}", string.Format("{0}",m.publisher))
				.Replace("{uri}", string.Format("{0}",m.uri))
				.Replace("{thumb}", string.Format("{0}",m.thumb))
				.Replace("{note}", string.Format("{0}",m.note));
		}
		
		static public string StringForBookMine(string input, DataRowView row)
		{
			return input
				.Replace("{id}", string.Format("{0}",row["id"]))
				.Replace("{publishdate}", string.Format("{0}",row["publishdate"]))
				.Replace("{title}", string.Format("{0}",row["title"]))
				.Replace("{author}", string.Format("{0}",row["author"]))
				.Replace("{publisher}", string.Format("{0}",row["publisher"]))
				.Replace("{uri}", string.Format("{0}",row["uri"]))
				.Replace("{thumb}", string.Format("{0}",row["thumb"]))
				.Replace("{note}", string.Format("{0}",row["note"]));
		}
		
		#region Queries
		/// <summary> not that we need it or anything </summary>
		internal const string Insert_BookMine = @"INSERT INTO [BookMine] (
[publishdate],
[title],
[author],
[publisher],
[uri],
[thumb],
[note])
VALUES(
@publishdate,
@title,
@author,
@publisher,
@uri,
@thumb,
@note);";
		/// <summary> not that we need it or anything </summary>
		internal const string Update_BookMine = @"UPDATE [BookMine] SET 
[publishdate] = @publishdate,
[title] = @title,
[author] = @author,
[publisher] = @publisher,
[uri] = @uri,
[thumb] = @thumb,
[note] = @note
WHERE [id] = @xid;";
		/// <summary> not that we need it or anything </summary>
		internal const string Select_BookMine = @"Select * From BookMine;";
		#endregion
		#region Properties
		public long? id { get;set; }
		public DateTime? publishdate { get;set; }
		public string title { get;set; }
		public string author { get;set; }
		public string publisher { get;set; }
		public string uri { get;set; }
		public string thumb { get;set; }
		public string note { get;set; }
		#endregion
		#region Constructors
		
		public BookMine(DataRowView row)
		{
			if (row["id"]!=DBNull.Value) this.id = row["id"] as long?;
			if (row["publishdate"]!=DBNull.Value) this.publishdate = row["publishdate"] as DateTime?;
			if (row["title"]!=DBNull.Value) this.title = row["title"] as string;
			if (row["author"]!=DBNull.Value) this.author = row["author"] as string;
			if (row["publisher"]!=DBNull.Value) this.publisher = row["publisher"] as string;
			if (row["uri"]!=DBNull.Value) this.uri = row["uri"] as string;
			if (row["thumb"]!=DBNull.Value) this.thumb = row["thumb"] as string;
			if (row["note"]!=DBNull.Value) this.note = row["note"] as string;
		}
		public DataRowView ToRow(DataRowView row)
		{
			if (row["id"]!=DBNull.Value) this.id = row["id"] as long?;
			if (row["publishdate"]!=DBNull.Value) this.publishdate = row["publishdate"] as DateTime?;
			if (row["title"]!=DBNull.Value) this.title = row["title"] as string;
			if (row["author"]!=DBNull.Value) this.author = row["author"] as string;
			if (row["publisher"]!=DBNull.Value) this.publisher = row["publisher"] as string;
			if (row["uri"]!=DBNull.Value) this.uri = row["uri"] as string;
			if (row["thumb"]!=DBNull.Value) this.thumb = row["thumb"] as string;
			if (row["note"]!=DBNull.Value) this.note = row["note"] as string;
			return row;
		}
		
		public BookMine(){}
		/// <summary>
		/// Used for cloning operations.
		/// <para>Particularly for Insert/Update SQL Queries due to the readonly PRIMARY KEY value.</para>
		/// </summary>
		public BookMine(BookMine value)
		{
			this.id = value.id;
			this.publishdate = value.publishdate;
			this.title = value.title;
			this.author = value.author;
			this.publisher = value.publisher;
			this.uri = value.uri;
			this.thumb = value.thumb;
			this.note = value.note;
		}
		#region NONONO
		#if NONONO
		
		/// <summary>
		/// Used for cloning operations.
		/// <para>Particularly for Insert/Update SQL Queries due to the readonly PRIMARY KEY value.</para>
		/// </summary>
		public BookMine(BookMine value)
		{
		this.id = value.id;
		this.SetFields(value);
		}
		#endif
		#endregion
		#endregion
		#region Utils
		
		/// <summary>
		/// Used for cloning operations.
		/// <para>Particularly for Insert/Update SQL Queries due to the readonly PRIMARY KEY value.</para>
		/// </summary>
		public void SetFields(BookMine value)
		{
			this.publishdate = value.publishdate;
			this.title = value.title;
			this.author = value.author;
			this.publisher = value.publisher;
			this.uri = value.uri;
			this.thumb = value.thumb;
			this.note = value.note;
		}
		
		// TODO: add if (usePrimary) to the primary key
		// an insert statement would not use or contain
		// a primary key value (or would contain a null,
		// hence we provide the oppertunity to neglect
		// it here.
		public SQLiteCommand Parameterize(SQLiteCommand cmd, bool usePrimary)
		{
			if (usePrimary) cmd.Parameters.AddWithValue("@xid", this.id);
			cmd.Parameters.AddWithValue("@publishdate", this.publishdate);
			cmd.Parameters.AddWithValue("@title", this.title);
			cmd.Parameters.AddWithValue("@author", this.author);
			cmd.Parameters.AddWithValue("@publisher", this.publisher);
			cmd.Parameters.AddWithValue("@uri", this.uri);
			cmd.Parameters.AddWithValue("@thumb", this.thumb);
			cmd.Parameters.AddWithValue("@note", this.note);
			return cmd;
		}
		#endregion
		#region template['?']['newTable']
		
		static public void SetupTable(DataTable table)
		{
			table.Columns.Add("id",typeof(Int64));
			table.Columns.Add("publishdate",typeof(DateTime));
			table.Columns.Add("title",typeof(String));
			table.Columns.Add("author",typeof(String));
			table.Columns.Add("publisher",typeof(String));
			table.Columns.Add("uri",typeof(String));
			table.Columns.Add("thumb",typeof(String));
			table.Columns.Add("note",typeof(String));
			table.PrimaryKey = new DataColumn[]{ table.Columns["id"] };
		}
		
		#endregion
		#region template['prime.struct']['struct rowfrom']
		
		static public BookMine FromRowView(DataRowView row)
		{
			BookMine model = new BookMine();
			if (row["id"]!=DBNull.Value) model.id = row["id"] as long?;
			if (row["publishdate"]!=DBNull.Value) model.publishdate = row["publishdate"] as DateTime?;
			if (row["title"]!=DBNull.Value) model.title = row["title"] as string;
			if (row["author"]!=DBNull.Value) model.author = row["author"] as string;
			if (row["publisher"]!=DBNull.Value) model.publisher = row["publisher"] as string;
			if (row["uri"]!=DBNull.Value) model.uri = row["uri"] as string;
			if (row["thumb"]!=DBNull.Value) model.thumb = row["thumb"] as string;
			if (row["note"]!=DBNull.Value) model.note = row["note"] as string;
			return model;
		}
		
		#endregion
		
		
		public DataSet GetAllData(string whereString)
		{
			string query = "select * from bookmine {and}";
			query = string.IsNullOrEmpty(whereString) 
				? query.Replace("{and}",whereString)
				: query.Replace("{and}",string.Empty);
			using (SQLiteQuery sqlite = new SQLiteQuery(loader.DataFile))
			{
				return sqlite.ExecuteSelect(query);
			}
		}
		
	}
	
}

